sonar.projectKey=certy-frontend
sonar.projectName=certy-frontend
sonar.projectVersion=1.0

# Rutas del código
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx

# Exclusiones
sonar.exclusions=node_modules/**,dist/**,build/**,.vite/**,src/vite-env.d.ts,**/*.test.ts,**/*.test.tsx

# Cobertura (Solo una vez)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Bypass de TS Config
sonar.typescript.tsconfigPaths=tsconfig.sonar.json
sonar.sourceEncoding=UTF-8