sonar.projectKey=hectorpq11_certyfront
sonar.organization=hectorpq11
sonar.projectName=CertyPro - Frontend

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.d.ts,**/test/**
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
